# Generated by Django 5.1.2 on 2024-11-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_livro_nome_remove_livro_site_livro_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
